export type Project = {
  id: number;
  slug: string;
  code: string;
  title: string;
  tagline: string;
  location: string;
  category: string;
  price: string;
  specs: string;
  image: string;
  description: string[];
  highlights: { label: string; value: string }[];
  amenities: string[];
  gallery: string[];
  architect: string;
  developer: string;
  possession: string;
  rera: string;
  landmarks: { label: string; distance: string }[];
  testimonial: { quote: string; author: string; role: string };
};

/* Real photography we hold — reused across projects that don't yet have
 * dedicated site photography, so every listing still reads as a curated set. */
const P1 = '/Projects/M3M/Artboard_4_1_-_8jpuMAmC4FGE.webp';
const P2 = '/Projects/M3M/Artboard_2_1_-_mYz5GbKAViun.webp';
const P3 = '/Projects/M3M/Artboard_3_1_-_lQRc3AupDBjT.webp';
const P4 = '/Projects/M3M%20Antalya/544304004_m3m-antalya-hills-gallery-3.webp';
const P5 = '/Projects/M3M%20Antalya/g5.webp';
const P6 = '/Projects/M3M%20Antalya/about_2_-_LKRZFgeqKGJ4_-_CfWwyPz3TLPk.webp';
const P7 = '/Projects/SIgnature/WhatsApp-Image-2026-02-26-at-124237-PM-Picsart-AiImageEnhancer.webp';
const P8 = '/Projects/SIgnature/WhatsApp-Image-2026-02-26-at-124128-PM-Picsart-AiImageEnhancer.webp';
const P9 = '/Projects/SIgnature/WhatsApp-Image-2026-02-26-at-124155-PM-Picsart-AiImageEnhancer.webp';
const P10 = '/Projects/SignatureDeluxe/image-Picsart-AiImageEnhancer-1-scaled.webp';
const P11 = '/Projects/SignatureDeluxe/g5%20(1).webp';
const P12 = '/Projects/SignatureDeluxe/544304004_m3m-antalya-hills-gallery-3%20(1).webp';

const RESIDENTIAL_AMENITIES = [
  '🏋️ Fully-Equipped Gymnasium',
  '🏊 Swimming Pool',
  '🛡️ 24×7 Security',
  '📷 CCTV Surveillance',
  '🚗 Dedicated Parking Space',
  '🍔 Cafeteria / Food Court',
  '🍸 Bar / Lounge',
  '🔋 Power Backup',
  '🌳 Landscaped Park',
  '🏠 Private Balcony',
  '❄️ Central Air Conditioning',
  "🧸 Kid's Play Area",
  '🎉 Party Hall',
  '🏀 Sports Facilities',
  '🏃 Jogging Track',
  '🚰 24×7 Water Supply',
];

const COMMERCIAL_AMENITIES = [
  '🛡️ 24×7 Security',
  '📷 CCTV Surveillance',
  '🚗 Dedicated Parking Space',
  '🔋 Power Backup',
  '🚰 Water Supply',
  '🍔 Cafeteria / Food Court',
];

const ADVISORY_ROLE = 'Real Estate Consultants, Gurugram';

export const PROJECTS: Project[] = [
  {
    id: 1,
    slug: 'm3m-mansion',
    code: 'GGN-113-A',
    title: 'M3M Mansion',
    tagline: 'Grand-lifestyle high-rise residences on the Dwarka Expressway.',
    location: 'Sector 113, Gurugram (Dwarka Expressway)',
    category: 'Residential',
    price: '₹3.77 – 26.87 Cr onwards',
    specs: '3, 3.5, 4, 4.5 BHK · 2080 – 3415 Sqft',
    image: P1,
    description: [
      'M3M India presents M3M Mansion, a premium residential project designed for those who enjoy a grand lifestyle. Located in the heart of Sector 113, Gurgaon, right on the Dwarka Expressway, it offers excellent connectivity and convenience as part of a large 250-acre master plan.',
      'M3M Mansion offers thoughtfully designed 3.5 BHK, 4.5 BHK, and 5 BHK residences, complete with a study, family lounge, and house help quarters. Apartment sizes range from 2,100 sq. ft. to 3,800 sq. ft., while penthouses span up to a lavish 7,000 sq. ft., each with a private deck and expansive balconies.',
      'Spread across 10.22 acres, the project features eight stylish high-rise towers, each rising to 32 floors, with air-conditioned lift lobbies and four high-speed elevators per tower. A 7.5-acre Central Vista and Club Imperial (with a five-star lobby, café, and temperature-controlled pool) anchor the resident experience.',
    ],
    highlights: [
      { label: 'Configuration', value: '3, 3.5, 4, 4.5 BHK Residences' },
      { label: 'Saleable Area', value: '2,080 – 3,415 Sqft (Penthouses up to 7,000 Sqft)' },
      { label: 'Project Area', value: '10.22 Acres' },
      { label: 'Towers', value: '8 Towers, 32 Floors Each' },
      { label: 'Developer', value: 'M3M India' },
      { label: 'Status', value: 'New Launch' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P1, P2, P3],
    architect: 'M3M India, In-House Design Studio',
    developer: 'M3M India',
    possession: 'New Launch',
    rera: 'Available on request',
    landmarks: [
      { label: 'Dwarka Expressway', distance: 'Direct Access' },
      { label: '250-Acre Master Plan', distance: 'Within Development' },
    ],
    testimonial: {
      quote:
        'M3M Mansion pairs a genuinely grand scale (eight towers, a 7.5-acre Central Vista) with the everyday convenience of the Dwarka Expressway address.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 2,
    slug: 'm3m-antalya-hills',
    code: 'GGN-079-A',
    title: 'M3M Antalya Hills',
    tagline: 'Low-rise independent floors framed by the Aravalli Hills.',
    location: 'Sector 79, Gurugram',
    category: 'Residential',
    price: '₹1.47 – 1.94 Cr onwards',
    specs: '2.5 / 3.5 BHK · 1159 – 1547 Sqft',
    image: P4,
    description: [
      'M3M Antalya Hills is a luxurious residential project offering low-rise independent floors in Sector 79, Gurgaon, designed for those who seek comfort, peace, and a refined lifestyle while staying well connected to the city.',
      'The project offers thoughtfully planned 2.5 BHK and 3.5 BHK independent floors, each featuring a private terrace and basement, with views toward the Aravalli Hills and a calm, resort-style ambience. The community follows a nature-first design philosophy, with vertical gardens, shaded walkways, and green parking zones woven into every cluster.',
      'Antalya Hills is planned as a multigenerational community with a decentralised layout. Each residential cluster is a self-sufficient pocket with parks, clubs, and essential amenities within a 2-minute walk.',
    ],
    highlights: [
      { label: 'Configuration', value: '2.5 BHK / 3.5 BHK Independent Floors' },
      { label: 'Saleable Area', value: '1,159 – 1,547 Sqft' },
      { label: 'Special Feature', value: 'Private Terrace + Basement per Unit' },
      { label: 'Developer', value: 'M3M India' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 79, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P4, P5, P6],
    architect: 'M3M India, In-House Design Studio',
    developer: 'M3M India',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'NH-8, SPR Road & KMP Expressway', distance: 'Well Connected' },
      { label: 'Upcoming Gurgaon ISBT, Railway Station & RRTS', distance: 'Nearby' },
      { label: 'IGI Airport', distance: 'Easy Access' },
      { label: 'DPS Manesar / Amity University', distance: 'Nearby' },
    ],
    testimonial: {
      quote:
        'A rare low-rise format in Gurugram: private terraces and basements, planned around a genuine nature-first, walk-to-everything community layout.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 3,
    slug: 'signature-sarvam',
    code: 'GGN-037-A',
    title: 'Signature Global Sarvam',
    tagline: 'Vaastu-rooted homes designed around light, air and calm.',
    location: 'Sector 37, Gurugram',
    category: 'Residential',
    price: '₹2.9 – 3.98 Cr',
    specs: '3, 3.5, 4 BHK · 1800 – 2495 Sqft',
    image: P7,
    description: [
      'Signature Global Sarvam is a thoughtfully crafted residential development rooted in the principles of ancient Vaastu and surrounded by nature\'s calm rhythm, more a living experience shaped by intention and balance than a conventional apartment block.',
      'Every tower is carefully positioned to make nature the project\'s greatest luxury, with homes designed to enjoy expansive skyline views, abundant daylight, and excellent cross-ventilation. Peaceful green pockets, open corridors, and landscaped surroundings encourage a slower, healthier, more balanced lifestyle.',
    ],
    highlights: [
      { label: 'Configuration', value: '3, 3.5, 4 BHK Homes' },
      { label: 'Saleable Area', value: '1,800 – 2,495 Sqft' },
      { label: 'Project Type', value: 'Affordable Premium Homes' },
      { label: 'Developer', value: 'Signature Global' },
      { label: 'Status', value: 'New Launch' },
      { label: 'Location', value: 'Sector 37, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P7, P8, P9],
    architect: 'Signature Global, In-House Design Team',
    developer: 'Signature Global',
    possession: 'New Launch',
    rera: 'Available on request',
    landmarks: [
      { label: 'Sector 37 Micro-Market', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'Sarvam plans its towers around Vaastu and daylight rather than density, the kind of quiet, considered layout that ages well.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 4,
    slug: 'signature-de-luxe-dxp',
    code: 'GGN-037-B',
    title: 'Signature Global De-luxe DXP',
    tagline: 'Spacious contemporary apartments for urban families.',
    location: 'Sector 37, Gurugram',
    category: 'Residential',
    price: '₹3.7 – 3.93 Cr',
    specs: '3, 3.5, 4.5 BHK · 2300 – 4500 Sqft',
    image: P10,
    description: [
      'Signature Global De-luxe DXP is a modern residential development in Sector 37, Gurugram offering spacious homes with premium design. The project features thoughtfully designed 3, 3.5 and 4.5 BHK apartments with large living areas, quality finishes and well-planned layouts for contemporary urban families.',
    ],
    highlights: [
      { label: 'Configuration', value: '3, 3.5, 4.5 BHK Apartments' },
      { label: 'Saleable Area', value: '2,300 – 4,500 Sqft' },
      { label: 'Project Type', value: 'Modern Residential Development' },
      { label: 'Developer', value: 'Signature Global' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 37, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P10, P11, P12],
    architect: 'Signature Global, In-House Design Team',
    developer: 'Signature Global',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Sector 37 Micro-Market', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'De-luxe DXP earns its name from the numbers alone: up to 4,500 sq ft of well-planned family living in Sector 37.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 5,
    slug: 'signature-titanium',
    code: 'GGN-071-A',
    title: 'Signature Global Titanium',
    tagline: 'Premium residences engineered for space and light.',
    location: 'Sector 71, Gurugram',
    category: 'Residential',
    price: '₹5.14 – 6.99 Cr',
    specs: '3.5 & 4.5 BHK · 2780 – 3780 Sqft',
    image: P1,
    description: [
      'Signature Global Titanium is a premium luxury residential project located in Sector 71, Gurugram, offering modern homes designed to deliver comfort, luxury and convenience for contemporary urban living.',
      'Titanium offers spacious residences ranging from 2,780 – 3,780 sq ft with well-planned layouts and elegant architecture. The project features 3.5 BHK and 4.5 BHK luxury apartments designed for maximum space, natural light and ventilation, set among landscaped gardens and green open spaces.',
    ],
    highlights: [
      { label: 'Configuration', value: '3.5 & 4.5 BHK Luxury Apartments' },
      { label: 'Saleable Area', value: '2,780 – 3,780 Sqft' },
      { label: 'Project Type', value: 'Premium Residential Apartments' },
      { label: 'Developer', value: 'Signature Global' },
      { label: 'Status', value: 'New Launch' },
      { label: 'Location', value: 'Sector 71, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P1, P5, P9],
    architect: 'Signature Global, In-House Design Team',
    developer: 'Signature Global',
    possession: 'New Launch',
    rera: 'Available on request',
    landmarks: [
      { label: 'NH-8', distance: 'Well Connected' },
      { label: 'Golf Course Extension Road', distance: 'Easy Access' },
      { label: 'Sohna Road', distance: 'Nearby' },
      { label: 'IGI Airport', distance: 'Easy Access' },
    ],
    testimonial: {
      quote:
        'Titanium\'s floor plans are unusually generous for the price point, 2,780 sq ft and up, with real cross-ventilation.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 6,
    slug: 'smart-world-sky-arch',
    code: 'GGN-069-A',
    title: 'Smart World Sky Arch',
    tagline: 'An iconic ultra-luxury high-rise on Golf Course Extension Road.',
    location: 'Sector 69, Gurugram',
    category: 'Residential',
    price: '₹5.02 – 6.96 Cr',
    specs: '3.5, 4.5 BHK · 2200 – 7000 Sqft',
    image: P2,
    description: [
      'Smart World Sky Arch is an ultra-luxury residential development located in Sector 69, Gurugram. This iconic project offers premium residences designed with modern architecture, luxury living spaces and world-class lifestyle features.',
      'Sky Arch offers spacious homes ranging from 2,200 – 7,000 sq ft, including premium 3.5 BHK and 4.5 BHK residences designed for maximum comfort, natural light and ventilation, framed by contemporary design and landscaped green areas.',
    ],
    highlights: [
      { label: 'Configuration', value: '3.5, 4.5 BHK Luxury Residences' },
      { label: 'Saleable Area', value: '2,200 – 7,000 Sqft' },
      { label: 'Project Type', value: 'Luxury High Rise Living' },
      { label: 'Developer', value: 'Smart World Developers' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 69, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P2, P6, P10],
    architect: 'Smart World Developers, In-House Design Team',
    developer: 'Smart World Developers',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Golf Course Extension Road', distance: 'Well Connected' },
      { label: 'Sohna Road', distance: 'Nearby' },
      { label: 'NH-8', distance: 'Easy Access' },
      { label: 'IGI Airport', distance: 'Easy Access' },
    ],
    testimonial: {
      quote:
        'Sky Arch\'s size range is the story here: 2,200 sq ft entry residences up to 7,000 sq ft, on one of Gurugram\'s most established corridors.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 7,
    slug: 'smart-world-edition',
    code: 'GGN-066-A',
    title: 'Smart World Edition',
    tagline: 'Modern urban homes with premium lifestyle amenities.',
    location: 'Sector 66, Gurugram',
    category: 'Residential',
    price: '₹5.40 Cr onwards',
    specs: '3, 4 BHK · 2900 – 3600 Sqft',
    image: P3,
    description: [
      'Smart World Edition is a premium luxury residential project located in Sector 66, Gurugram, designed to offer modern homes with world-class architecture, spacious layouts and premium lifestyle amenities.',
      'Edition offers luxurious residences ranging from 2,900 – 3,600 sq ft, with elegant 3 BHK and 4 BHK apartments designed for comfort, space and modern urban living, surrounded by landscaped gardens and open green spaces.',
    ],
    highlights: [
      { label: 'Configuration', value: '3, 4 BHK Apartments' },
      { label: 'Saleable Area', value: '2,900 – 3,600 Sqft' },
      { label: 'Project Type', value: 'Modern Urban Homes' },
      { label: 'Developer', value: 'Smart World Developers' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 66, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P3, P7, P11],
    architect: 'Smart World Developers, In-House Design Team',
    developer: 'Smart World Developers',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Golf Course Extension Road', distance: 'Well Connected' },
      { label: 'Sohna Road', distance: 'Nearby' },
      { label: 'NH-8', distance: 'Easy Access' },
      { label: 'IGI Airport', distance: 'Easy Access' },
    ],
    testimonial: {
      quote:
        'Edition keeps to just two configurations, 3 and 4 BHK, and uses the discipline to give every unit genuinely large room proportions.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 8,
    slug: 'ganga-valley',
    code: 'GGN-078-A',
    title: 'Ganga Valley',
    tagline: 'Independent-floor township living in Sector 78.',
    location: 'Sector 78, Gurugram',
    category: 'Residential',
    price: '₹2.5 Cr + PLC + GST',
    specs: '3.5, 4.5 BHK · 1900 – 2500 Sqft',
    image: P4,
    description: [
      'Ganga Valley is a premium residential development located in Sector 78, Gurugram, offering modern independent floors designed for comfortable living with contemporary architecture and functional layouts.',
      'Ganga Valley offers spacious residences ranging from 1,900 – 2,500 sq ft and features 3.5 and 4.5 BHK units, providing private and spacious homes ideal for modern families, within a well-planned township infrastructure and a well-connected location.',
    ],
    highlights: [
      { label: 'Configuration', value: '3.5, 4.5 BHK Independent Floors' },
      { label: 'Saleable Area', value: '1,900 – 2,500 Sqft' },
      { label: 'Project Type', value: 'Residential Township' },
      { label: 'Developer', value: 'Ganga Realty' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 78, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P4, P8, P12],
    architect: 'Ganga Realty, In-House Design Team',
    developer: 'Ganga Realty',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Sector 78 Micro-Market', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'Ganga Valley reads as a township rather than a single tower, genuine independent floors with room to breathe.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 9,
    slug: 'whiteland-westin-residences',
    code: 'GGN-103-A',
    title: 'Whiteland Westin Residences',
    tagline: 'Branded ultra-luxury residences in Sector 103.',
    location: 'Sector 103, Gurugram',
    category: 'Residential',
    price: '₹5.50 – 7.50 Cr',
    specs: '3, 4 BHK · 2500 – 4329 Sqft',
    image: P5,
    description: [
      'Whiteland Westin Residences is an ultra-luxury residential development located in Sector 103, Gurugram, designed to deliver premium living with modern architecture, elegant interiors and world-class lifestyle amenities.',
      'Westin Residences offers spacious luxury homes ranging from 2,500 – 4,329 sq ft, with beautifully designed 3 BHK and 4 BHK residences featuring large layouts, modern design and high-end finishes, set within landscaped surroundings and open green areas.',
    ],
    highlights: [
      { label: 'Configuration', value: '3, 4 BHK Branded Residences' },
      { label: 'Saleable Area', value: '2,500 – 4,329 Sqft' },
      { label: 'Project Type', value: 'Branded Luxury Residences' },
      { label: 'Developer', value: 'Whiteland Corporation' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 103, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P5, P9, P1],
    architect: 'Whiteland Corporation, In-House Design Team',
    developer: 'Whiteland Corporation',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Major Roads & Business Hubs', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'Westin Residences carries the Westin brand into private ownership. The finish quality shows in the details.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 10,
    slug: 'sobha-arya',
    code: 'GGN-080-A',
    title: 'Sobha Arya (Sobha Aranya)',
    tagline: 'Ultra-luxury residences from one of India\'s most trusted builders.',
    location: 'Sector 80, Gurugram',
    category: 'Residential',
    price: '₹7 – 9.75 Cr',
    specs: '3, 4 BHK · 2836 – 4285 Sqft',
    image: P6,
    description: [
      'Sobha Arya (Sobha Aranya) is an ultra-luxury residential development located in Sector 80, Gurugram, designed to provide premium living with elegant architecture, modern interiors and world-class lifestyle facilities.',
      'Sobha Arya offers spacious luxury residences ranging from 2,836 – 4,285 sq ft, with beautifully designed 3 BHK and 4 BHK apartments featuring large layouts, modern aesthetics and high-end specifications, surrounded by lush green landscapes and open spaces.',
    ],
    highlights: [
      { label: 'Configuration', value: '3, 4 BHK Apartments' },
      { label: 'Saleable Area', value: '2,836 – 4,285 Sqft' },
      { label: 'Project Type', value: 'Luxury Residential Project' },
      { label: 'Developer', value: 'Sobha Limited' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 80, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P6, P10, P2],
    architect: 'Sobha Limited, In-House Design Team',
    developer: 'Sobha Limited',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Major Highways & Business Districts', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'Sobha\'s build-quality reputation is the headline at Arya, large layouts backed by a developer known for finishing what it promises.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 11,
    slug: 'signature-daxin-vistas',
    code: 'GGN-036-A',
    title: 'Signature Global Daxin Vistas',
    tagline: 'Practical, well-connected 3 BHK homes in Sector 36.',
    location: 'Sector 36, Gurugram',
    category: 'Residential',
    price: '₹1.97 – 2.20 Cr',
    specs: '3 BHK · 1525 – 1550 Sqft',
    image: P7,
    description: [
      'Signature Global Daxin Vistas is a modern residential project located in Sector 36, Gurugram, designed to provide comfortable living with well-planned homes, modern architecture and quality construction.',
      'Daxin Vistas offers spacious residences ranging from 1,525 – 1,550 sq ft, with thoughtfully designed 3 BHK apartments that provide functional layouts and comfortable living spaces for modern families, in a location with good connectivity to major roads and business hubs.',
    ],
    highlights: [
      { label: 'Configuration', value: '3 BHK Apartments' },
      { label: 'Saleable Area', value: '1,525 – 1,550 Sqft' },
      { label: 'Project Type', value: 'Modern Residential Apartments' },
      { label: 'Developer', value: 'Signature Global' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 36, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P7, P11, P3],
    architect: 'Signature Global, In-House Design Team',
    developer: 'Signature Global',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Sector 36 Micro-Market', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'Daxin Vistas keeps things straightforward, a single, well-built 3 BHK configuration at an accessible entry price.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 12,
    slug: 'signature-cloverdale',
    code: 'GGN-071-B',
    title: 'Signature Global Cloverdale',
    tagline: 'Stylish architecture and spacious layouts in Sector 71.',
    location: 'Sector 71, Gurugram',
    category: 'Residential',
    price: '₹3.87 – 5.14 Cr',
    specs: '3, 4 BHK · 2095 – 3480 Sqft',
    image: P8,
    description: [
      'Signature Global Cloverdale is a premium residential project located in Sector 71, Gurugram, designed to offer modern living with stylish architecture, spacious layouts and high-quality construction.',
      'Cloverdale offers well-designed residences ranging from 2,095 – 3,480 sq ft, with beautifully planned 3 BHK and 4 BHK apartments providing comfortable living spaces for modern families, backed by landscaped surroundings and open green areas.',
    ],
    highlights: [
      { label: 'Configuration', value: '3, 4 BHK Apartments' },
      { label: 'Saleable Area', value: '2,095 – 3,480 Sqft' },
      { label: 'Project Type', value: 'Modern Residential Community' },
      { label: 'Developer', value: 'Signature Global' },
      { label: 'Status', value: 'New Launch' },
      { label: 'Location', value: 'Sector 71, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P8, P12, P4],
    architect: 'Signature Global, In-House Design Team',
    developer: 'Signature Global',
    possession: 'New Launch',
    rera: 'Available on request',
    landmarks: [
      { label: 'Major Roads & Business Hubs', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'Cloverdale\'s Sector 71 address puts it in the same corridor as several established launches, at a comparatively accessible ticket size.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 13,
    slug: 'm3m-forestia',
    code: 'GGN-MSR-A',
    title: 'M3M Forestia',
    tagline: 'A retail and residential destination in Manesar.',
    location: 'Manesar, Gurugram',
    category: 'Residential',
    price: '₹2.5 Cr onwards',
    specs: '3, 3.5 BHK · 1905 – 1910 Sqft',
    image: P9,
    description: [
      'M3M Forestia is a premium residential development located in Manesar, Gurugram, designed to provide modern living with elegant architecture, contemporary interiors and world-class lifestyle facilities.',
      'Forestia offers spacious luxury residences ranging from 1,905 – 1,910 sq ft, with beautifully designed 3 BHK and 3.5 BHK apartments featuring well-planned layouts, modern design and premium specifications, surrounded by open spaces and thoughtfully planned infrastructure.',
    ],
    highlights: [
      { label: 'Configuration', value: '3, 3.5 BHK Apartments' },
      { label: 'Saleable Area', value: '1,905 – 1,910 Sqft' },
      { label: 'Project Type', value: 'Retail & Residential Destination' },
      { label: 'Developer', value: 'M3M India' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Manesar, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P9, P1, P5],
    architect: 'M3M India, In-House Design Studio',
    developer: 'M3M India',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Major Highways & Industrial Hubs', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'Forestia bundles residential and retail in one Manesar address, useful for owners who want daily conveniences on the doorstep.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 14,
    slug: 'm3m-elie-saab',
    code: 'GGN-111-A',
    title: 'M3M Elie Saab',
    tagline: 'Designer-branded ultra-luxury residences.',
    location: 'Sector 111, Gurugram',
    category: 'Residential',
    price: '₹15 Cr onwards',
    specs: '4.5 BHK · 4350 Sqft',
    image: P10,
    description: [
      'M3M Elie Saab is an ultra-luxury residential development located in Sector 111, Gurugram, designed to offer premium living with elegant architecture, designer interiors and world-class lifestyle amenities.',
      'Elie Saab offers spacious luxury residences of 4,350 sq ft, with beautifully designed 4.5 BHK apartments featuring expansive layouts, premium fittings and high-end specifications, thoughtfully planned with landscaped surroundings and modern infrastructure.',
    ],
    highlights: [
      { label: 'Configuration', value: '4.5 BHK Designer Residences' },
      { label: 'Saleable Area', value: '4,350 Sqft' },
      { label: 'Project Type', value: 'Luxury Residences (Designer Branded)' },
      { label: 'Developer', value: 'M3M India' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 111, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P10, P2, P6],
    architect: 'Elie Saab Design Collaboration',
    developer: 'M3M India',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Dwarka Expressway', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'A designer-branded collaboration at this scale is rare in Gurugram. Elie Saab is priced and positioned accordingly.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 15,
    slug: 'signature-twin-tower',
    code: 'GGN-084-A',
    title: 'Signature Global Twin Tower',
    tagline: 'Elegant twin-tower residences in Sector 84.',
    location: 'Sector 84, Gurugram',
    category: 'Residential',
    price: '₹5.57 – 7.95 Cr',
    specs: '3, 3.5, 4.5 BHK · 1892 – 3785 Sqft',
    image: P11,
    description: [
      'Signature Global Twin Tower is a premium residential development located in Sector 84, Gurugram, designed to offer modern living with elegant architecture, spacious interiors and world-class lifestyle facilities.',
      'Twin Tower offers luxurious residences ranging from 1,892 – 3,785 sq ft, with beautifully designed 3 BHK, 3.5 BHK and 4.5 BHK apartments featuring spacious layouts, contemporary design and high-end specifications, set among landscaped greens and open spaces.',
    ],
    highlights: [
      { label: 'Configuration', value: '3, 3.5, 4.5 BHK Apartments' },
      { label: 'Saleable Area', value: '1,892 – 3,785 Sqft' },
      { label: 'Project Type', value: 'Twin Residential Towers' },
      { label: 'Developer', value: 'Signature Global' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 84, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P11, P3, P7],
    architect: 'Signature Global, In-House Design Team',
    developer: 'Signature Global',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Major Highways & Business Hubs', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'Twin Tower spans a wide configuration range in one address, useful for families comparing 3 BHK against 4.5 BHK side by side.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 16,
    slug: 'presidential-elan-106',
    code: 'GGN-106-A',
    title: 'Presidential (Elan 106)',
    tagline: 'Expansive luxury residences on the Dwarka Expressway.',
    location: 'Sector 106, Gurugram',
    category: 'Residential',
    price: '₹4.6 Cr onwards',
    specs: '3, 4, 5 BHK · 2450 – 7200 Sqft',
    image: P12,
    description: [
      'Presidential is a premium residential development located in Sector 106, Gurugram, designed to provide modern living with elegant architecture, luxurious interiors and world-class lifestyle amenities.',
      'Presidential offers spacious luxury residences ranging from 2,450 – 7,200 sq ft, with beautifully designed 3 BHK, 4 BHK and 5 BHK apartments featuring expansive layouts, stylish design and high-end specifications, surrounded by landscaped green areas and open spaces.',
    ],
    highlights: [
      { label: 'Configuration', value: '3, 4, 5 BHK Apartments' },
      { label: 'Saleable Area', value: '2,450 – 7,200 Sqft' },
      { label: 'Project Type', value: 'Luxury Residential' },
      { label: 'Developer', value: 'Elan Group' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 106, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P12, P4, P8],
    architect: 'Elan Group, In-House Design Team',
    developer: 'Elan Group',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Dwarka Expressway', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'A 2,450 to 7,200 sq ft range under one roof is unusual. Presidential effectively covers three buyer segments at once.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 17,
    slug: 'elan-the-statement',
    code: 'GGN-049-A',
    title: 'Elan The Statement',
    tagline: '4 BHK residences and penthouses on Sohna Road.',
    location: 'Sector 49, Gurugram',
    category: 'Residential',
    price: '₹10 Cr onwards',
    specs: '4 BHK & Penthouse · 4300+ Sqft',
    image: P1,
    description: [
      'Elan The Statement is a luxury residential development located in Sector 49, Gurugram, designed to provide modern living with elegant architecture, spacious interiors and premium lifestyle amenities.',
      'The Statement offers expansive luxury residences from 4,300+ sq ft, with beautifully designed 4 BHK and penthouse apartments featuring large layouts, contemporary design and high-end specifications, surrounded by lush green landscapes and open spaces.',
    ],
    highlights: [
      { label: 'Configuration', value: '4 BHK & Penthouse' },
      { label: 'Saleable Area', value: '4,300+ Sqft' },
      { label: 'Project Type', value: 'Residential Retail Complex' },
      { label: 'Developer', value: 'Elan Group' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 49, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P1, P5, P9],
    architect: 'Elan Group, In-House Design Team',
    developer: 'Elan Group',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Sohna Road', distance: 'Well Connected' },
      { label: 'Golf Course Extension Road', distance: 'Nearby' },
    ],
    testimonial: {
      quote:
        'The Statement pairs a residential-retail format with genuinely large penthouse-class floor plans starting above 4,300 sq ft.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 18,
    slug: 'smart-world-dxp',
    code: 'GGN-113-B',
    title: 'Smart World DXP',
    tagline: 'A mixed-use retail and residential hub on Dwarka Expressway.',
    location: 'Sector 113, Gurugram',
    category: 'Residential',
    price: '₹3.87 Cr onwards',
    specs: '2.5, 3.5, 4.5 BHK · 1121 – 2326 Sqft',
    image: P2,
    description: [
      'Smart World DXP is a premium residential development located in Sector 113, Gurugram, designed to offer modern living with stylish architecture, contemporary interiors and world-class lifestyle amenities.',
      'DXP offers spacious luxury residences ranging from 1,121 – 2,326 sq ft, with beautifully designed 2.5 BHK, 3.5 BHK and 4.5 BHK apartments featuring smart layouts, modern design and premium specifications, surrounded by landscaped green spaces.',
    ],
    highlights: [
      { label: 'Configuration', value: '2.5, 3.5, 4.5 BHK Apartments' },
      { label: 'Saleable Area', value: '1,121 – 2,326 Sqft' },
      { label: 'Project Type', value: 'Mixed Use, Retail & Residential Hub' },
      { label: 'Developer', value: 'Smart World Developers' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 113, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P2, P6, P10],
    architect: 'Smart World Developers, In-House Design Team',
    developer: 'Smart World Developers',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Dwarka Expressway', distance: 'Well Connected' },
      { label: 'IGI Airport', distance: 'Easy Access' },
    ],
    testimonial: {
      quote:
        'DXP\'s mixed-use format means retail and daily conveniences sit within the same address as the residences.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 19,
    slug: 'natures-court',
    code: 'GGN-MSR-B',
    title: 'Natures Court',
    tagline: 'Compact, well-planned homes in Manesar.',
    location: 'Manesar, Gurugram',
    category: 'Residential',
    price: '₹1.75 Cr',
    specs: '2, 2.5 BHK · 1339 – 1360 Sqft',
    image: P3,
    description: [
      'Natures Court is a modern residential development located in Manesar, designed to offer comfortable living with contemporary architecture, well-planned interiors and premium lifestyle amenities.',
      'Natures Court offers thoughtfully designed homes ranging from 1,339 – 1,360 sq ft, with stylish 2 and 2.5 BHK apartments featuring smart layouts, modern design and quality specifications, surrounded by landscaped greenery and well-planned infrastructure.',
    ],
    highlights: [
      { label: 'Configuration', value: '2, 2.5 BHK Apartments' },
      { label: 'Saleable Area', value: '1,339 – 1,360 Sqft' },
      { label: 'Project Type', value: 'Retail & Investment Project' },
      { label: 'Developer', value: 'Natures Court' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Manesar, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P3, P7, P11],
    architect: 'Natures Court, In-House Design Team',
    developer: 'Natures Court',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Major Highways & Industrial Hubs', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'At this price point, Natures Court is one of the more accessible entry points into the Manesar corridor.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 20,
    slug: 'aipl-revante-103',
    code: 'GGN-103-B',
    title: 'AIPL Revante 103',
    tagline: 'Contemporary residences with wide configuration choice.',
    location: 'Sector 103, Gurugram',
    category: 'Residential',
    price: '₹2.88 – 3.60 Cr',
    specs: '2, 3, 4 BHK · 2196 – 3211 Sqft',
    image: P4,
    description: [
      'AIPL Revante 103 (also referred to as AIPL Riveria 103) is a premium residential development located in Sector 103, Gurugram, designed to offer modern living with elegant architecture, spacious interiors and world-class lifestyle amenities.',
      'Revante 103 offers beautifully designed residences ranging from 2,196 – 3,211 sq ft, with spacious 2 BHK, 3 BHK and 4 BHK apartments featuring contemporary layouts, stylish interiors and high-quality specifications, surrounded by landscaped green spaces.',
    ],
    highlights: [
      { label: 'Configuration', value: '2, 3, 4 BHK Apartments' },
      { label: 'Saleable Area', value: '2,196 – 3,211 Sqft' },
      { label: 'Project Type', value: 'Residential' },
      { label: 'Developer', value: 'AIPL (Advance India Projects Limited)' },
      { label: 'Status', value: 'New Launch' },
      { label: 'Location', value: 'Sector 103, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P4, P8, P12],
    architect: 'AIPL, In-House Design Team',
    developer: 'AIPL (Advance India Projects Limited)',
    possession: 'New Launch',
    rera: 'Available on request',
    landmarks: [
      { label: 'Dwarka Expressway', distance: 'Well Connected' },
    ],
    testimonial: {
      quote:
        'Revante 103 spans 2 BHK through 4 BHK in one launch, a practical range for families upgrading within the same address.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 21,
    slug: 'altus-sobha',
    code: 'GGN-106-B',
    title: 'Altus by Sobha',
    tagline: 'Elegant 4 & 5 BHK residences on Dwarka Expressway.',
    location: 'Sector 106, Gurugram',
    category: 'Residential',
    price: '₹6.5 Cr onwards',
    specs: '4, 5 BHK · 2870 – 3853 Sqft',
    image: P5,
    description: [
      'Altus is a premium residential development located in Sector 106, Gurugram, designed to provide modern living with elegant architecture, spacious interiors and world-class lifestyle amenities.',
      'Altus offers luxurious residences ranging from 2,870 – 3,853 sq ft, with beautifully designed 4 and 5 BHK apartments featuring large layouts, contemporary design and premium specifications, set among landscaped green areas and thoughtfully planned infrastructure.',
    ],
    highlights: [
      { label: 'Configuration', value: '4, 5 BHK Apartments' },
      { label: 'Saleable Area', value: '2,870 – 3,853 Sqft' },
      { label: 'Project Type', value: 'Residential Business Spaces' },
      { label: 'Developer', value: 'Sobha Limited' },
      { label: 'Status', value: 'Under Construction' },
      { label: 'Location', value: 'Sector 106, Gurugram' },
    ],
    amenities: RESIDENTIAL_AMENITIES,
    gallery: [P5, P9, P1],
    architect: 'Sobha Limited, In-House Design Team',
    developer: 'Sobha Limited',
    possession: 'Under Construction',
    rera: 'Available on request',
    landmarks: [
      { label: 'Dwarka Expressway', distance: 'Well Connected' },
      { label: 'IGI Airport', distance: 'Easy Access' },
    ],
    testimonial: {
      quote:
        'Altus brings Sobha\'s build quality to a strictly 4 & 5 BHK format, a focused offer for larger families.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
  {
    id: 22,
    slug: 'omaxe',
    code: 'DWK-019-A',
    title: 'Omaxe',
    tagline: 'Integrated commercial spaces in Dwarka Sector 19.',
    location: 'Sector 19, Dwarka, New Delhi',
    category: 'Commercial',
    price: '₹50 Lacs onwards',
    specs: 'Virtual & Lockable Shops · 40 – 3000 Sqft',
    image: P6,
    description: [
      'Omaxe is a premium commercial development located in Dwarka Sector 19, designed to offer modern retail and business spaces with smart infrastructure and high investment potential.',
      'Omaxe offers a wide range of commercial units starting from 40 – 3,000 sq ft, suitable for shops, offices and retail businesses, and features virtual & lockable shops that provide flexibility, security and convenience for business owners and investors.',
      'Strategically located in Dwarka Sector 19, the project enjoys excellent connectivity to major roads, residential hubs and commercial zones, with attractive pricing starting from ₹50 Lacs onwards.',
    ],
    highlights: [
      { label: 'Property Types', value: 'Virtual & Lockable Shops' },
      { label: 'Unit Size Range', value: '40 – 3,000 Sqft' },
      { label: 'Project Type', value: 'Integrated Commercial' },
      { label: 'Developer', value: 'Omaxe' },
      { label: 'Status', value: 'New Launch' },
      { label: 'Location', value: 'Sector 19, Dwarka, New Delhi' },
    ],
    amenities: COMMERCIAL_AMENITIES,
    gallery: [P6, P10, P2],
    architect: 'Omaxe, In-House Design Team',
    developer: 'Omaxe',
    possession: 'New Launch',
    rera: 'Available on request',
    landmarks: [
      { label: 'Major Roads & Residential Hubs', distance: 'Well Connected' },
      { label: 'Commercial Zones', distance: 'Nearby' },
    ],
    testimonial: {
      quote:
        'Omaxe\'s unit sizes start as low as 40 sq ft, a genuinely low entry ticket for first-time commercial investors.',
      author: 'Infraguru Advisory Team',
      role: ADVISORY_ROLE,
    },
  },
];

export function getProjectById(id: string): Project | undefined {
  return PROJECTS.find((p) => String(p.id) === id);
}
